- hosts: k8s-slave
  tasks:
 
  - name: Install docker-ce
    command: amazon-linux-extras install docker -y

  - name: Start the docker services
    command: service docker start
  
  - name: Configure repository for K8s
    yum_repository:
      description: kubernetes
      name: kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled: 1
      gpgcheck: 1
      repo_gpgcheck: 1
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude: kubelet kubeadm kubectl
    ignore_errors: yes
 
  - name: Installing K8s packges
    yum:
      name: kubelet
      disable_excludes: kubernetes

  - name: Installing K8s packges
    yum:
      name: kubeadm
      disable_excludes: kubernetes

  - name: Installing K8s packges
    yum:
      name: kubectl
      disable_excludes: kubernetes

  - name: Enable kubelet services
    command: systemctl enable --now kubelet

  - name: Change docker drivers
    copy:
      dest: /etc/docker/daemon.json
      content: '{
  "exec-opts": ["native.cgroupdriver=systemd"]
}'

 
  - name: Start the docker services
    service:
      name: docker
      state: restarted

  - name: Download iproute-tc
    yum:
      name: iproute-tc

      

  - copy: 
      dest:  /etc/sysctl.d/k8s.conf
      src: /home/ec2-user/k8s_conf.txt

  - command: sysctl --system

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh
